version: '3.8'

volumes:
  config:
    external: false

services:
  openvpn-client:
    image: rlukawski/openvpn-client:latest
    privileged: true
    platform: linux/arm64
    
    build:
      context: ./openvpn
      dockerfile: ./Dockerfile
    volumes:
      - /etc/openvpn/client:/etc/openvpn/client

  hostapd-client:
    image: rlukawski/hostapd-client:latest
    privileged: true
    platform: linux/arm64
    build:
      context: ./hostapd
      dockerfile: ./Dockerfile
    networks:
      vlan:
        ipv4_address: 192.168.5.2
    

networks:
  vlan:
    driver: macvlan
    driver_opts:
      parent: eth0  
    ipam:
      config:
        - subnet: 192.168.5.0/24
          gateway: 192.168.5.1
          ip_range: 192.168.5.0/24    
