- name: Add configuration for wlan0 to /etc/network/interfaces
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    line: "{{ item }}"
    insertafter: EOF
  loop:
    - "allow-hotplug wlan0"
    - "iface wlan0 inet static"
    - "  address 192.168.1.1"
    - "  netmask 255.255.255.0"
  notify: Restart networking

- name: Create startup script for iptables rule
  copy:
    dest: /etc/network/if-up.d/iptables-rules
    content: |
      #!/bin/sh
      iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
    mode: '0755'
  become: yes

- name: Set dns=dnsmasq in the [main] section in NetworkManager.conf
  ansible.builtin.ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: dnsmasq
    backup: yes

- name: Restart networking
  ansible.builtin.command: systemctl restart networking

