version: '3.8'

volumes:
  openvpn:
    external: false

services:
  openvpn:
    image: rlukawski/openvpn:latest
    privileged: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - openvpn:/etc/openvpn
    ports:
      - "1194:1194/udp"
