- name: Add configuration for wlan0 to /etc/network/interfaces
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    line: "{{ item }}"
    insertafter: EOF
  loop:
    - "allow-hotplug wlan0"
    - "iface wlan0 inet static"
    - "  address 192.168.1.1"
    - "  netmask 255.255.255.0"
  notify: Restart networking

- name: Create startup script for networking
  copy:
    dest: /etc/network/if-up.d/hostapd
    content: |
      #!/bin/bash
      iptables -t nat -F
      sysctl net.ipv4.ip_forward=1
      if [ "$IFACE" = "tun0" ]; then
        if [ "$MODE" = "start" ]; then
          iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
        fi
      fi

    mode: '0755'
  become: yes

- name: Set dns=dnsmasq in the [main] section in NetworkManager.conf
  ansible.builtin.ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: dnsmasq
    backup: yes

- name: Configure DHCP Server
  ansible.builtin.lineinfile:
    path: /etc/NetworkManager/dnsmasq.d/hostapd
    line: "{{ item }}"
    create: yes
  loop:
    - 'interface=wlan0'
    - 'dhcp-range=192.168.1.50,192.168.1.150,12h'
    - 'bind-interfaces'

- name: Restart networking
  ansible.builtin.command: systemctl restart networking

