- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - openvpn
      - iptables
    state: present

- name: Ensure OpenVPN directory exists
  file:
    path: /etc/openvpn/client
    state: directory
    mode: "0755"

- name: Copy openvpn configuration file
  copy:
    src: ./client.conf
    dest: /etc/openvpn/client/

- name: Add specific routes to OpenVPN configuration
  lineinfile:
    path: /etc/openvpn/client/client.conf
    line: "route 62.179.1.0 255.255.255.0 net_gateway"
    create: yes
    state: present

- name: Unmask openvpn-client service
  become: yes
  systemd:
    name: openvpn-client
    masked: no
    daemon_reload: yes

- name: Enable and start openvpn-client service
  become: yes
  systemd:
    name: openvpn-client
    enabled: yes
    state: started
    daemon_reload: yes

- name: Ensure openvpn-client is enabled at boot
  become: yes
  systemd:
    name: openvpn-client
    enabled: yes
