- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - openvpn
      - iptables
    state: present

- name: Copy openvpn service file
  copy:
    src: services/openvpn-client.service
    dest: /etc/systemd/system/

- name: Ensure OpenVPN directory exists
  file:
    path: /etc/openvpn/client
    state: directory
    mode: "0755"

- name: Copy openvpn configuration file
  copy:
    src: ./client.conf
    dest: /etc/openvpn/client/

- name: Add specific routes to OpenVPN configuration
  lineinfile:
    path: /etc/openvpn/client/client.conf
    line: "route 62.179.1.0 255.255.255.0 net_gateway"
    create: yes
    state: present

- name: Set up OpenVPN service
  systemd:
    name: openvpn-client.service
    enabled: yes
    state: started
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"

- name: Configure OpenVPN to start on boot
  shell: systemctl enable openvpn-client
  when: ansible_service_mgr == "systemd"
