version: "3.8"

volumes:
  certs:
    external: false

services:
  prometheus:
    image: prom/prometheus:latest
    # ports:
    #   - 9090:9090

  grafana:
    image: rlukawski/grafana:latest
    build:
      context: ./grafana
      dockerfile: ./Dockerfile

  grafana-nginx:
    image: rlukawski/grafana-nginx:latest
    volumes:
      - certs:/etc/letsencrypt/
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - grafana
