version: "3.8"

volumes:
  certs:
    external: false
  grafana:
    external: false

services:
  prometheus:
    image: prom/prometheus:latest

  grafana:
    image: grafana/grafana:10.4.2
    volumes:
      - grafana:/var/lib/grafana
    # build:
    #   context: ./grafana
    #   dockerfile: ./Dockerfile

  grafana-nginx:
    image: rlukawski/grafana-nginx:latest
    volumes:
      - certs:/etc/letsencrypt/
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - grafana
