version: "3.8"

volumes:
  certs:
    external: false
  grafana-data:
    external: false

services:
  node-exporter:
    image: prom/node-exporter:v1.3.1
    network_mode: host

  prometheus:
    image: rlukawski/prometheus:latest
    network_mode: host
    build:
      context: ./prometheus
      dockerfile: ./Dockerfile
    depends_on:
      - node-exporter

  grafana:
    image: grafana/grafana:10.4.2
    network_mode: host
    volumes:
      - grafana-data:/var/lib/grafana
    # ports:
    #   - 3000:3000

  grafana-nginx:
    image: rlukawski/grafana-nginx:latest
    volumes:
      - certs:/etc/letsencrypt/
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    # ports:
    #   - 80:80
    #   - 443:443
    depends_on:
      - grafana
